- name: pki dir exists
  file:
    path: '{{ k8s_node__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Keys and certificates for kubelet
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kubelet-{{ ansible_facts.fqdn }}.key'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kubelet-{{ ansible_facts.fqdn }}.crt'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0644

- name: Keys and certificates for kube-proxy
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-proxy.key'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-proxy.crt'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0644

- name: k8s CA certificates is installed
  copy:
    src: '{{ item }}'
    dest: '{{ k8s_node__pki_dir }}'
    owner: kubernetes
    group: kubernetes
    mode: 0644
  loop:
  - '{{ k8s__local_shared_dir }}/ca.crt'
