- name: pki dir exists
  file:
    path: '{{ k8s_node__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Keys and certificates for the user 'root'
  block:
  - name: Keys are installed
    copy:
      src: '{{ item }}'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0600
    loop:
    - '{{ k8s__local_shared_dir }}/kube-proxy.key'
  - name: Certificates are installed
    copy:
      src: '{{ item }}'
      dest: '{{ k8s_node__pki_dir }}'
      owner: root
      group: root
      mode: 0644
    loop:
    - '{{ k8s__local_shared_dir }}/kube-proxy.crt'

- name: k8s CA certificates is installed
  copy:
    src: '{{ item }}'
    dest: '{{ k8s_node__pki_dir }}'
    owner: kubernetes
    group: kubernetes
    mode: 0644
  loop:
  - '{{ k8s__local_shared_dir }}/ca.crt'
