- name: cni dirs exist
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
  - '{{ k8s_node__kubelet_cni_conf_dir }}'
  - '{{ k8s_node__kubelet_cni_bin_dir }}'

- name: cni plugin bins are installed
  vars:
    _cni_plugins_archive_basename: cni-plugins-linux-amd64-{{ k8s_node__cni_plugins_version }}
    _cni_plugins_archive: '{{ _cni_plugins_archive_basename }}.tgz'
  block:
  - name: cni plugins archive is downloaded
    get_url:
      url: '{{ k8s_node__cni_plugins_archive_download_url_base }}/{{ k8s_node__cni_plugins_version }}/{{ _cni_plugins_archive }}'
      dest: '{{ k8s__remote_tmp_dir }}/{{ _cni_plugins_archive }}'
      checksum: '{{ k8s_node__cni_plugins_archive_checksum }}'
    register: _get_url_result
  - name: cni plugins archive is extracted
    unarchive:
      src: '{{ k8s__remote_tmp_dir }}/{{ _cni_plugins_archive }}'
      remote_src: true
      dest: '{{ k8s_node__kubelet_cni_bin_dir }}'
      owner: root
      group: root
      mode: 0755
    when: _get_url_result.changed

- name: cni bins are owned by root
  file:
    path: '{{ k8s_node__kubelet_cni_bin_dir }}'
    owner: root
    group: root
    mode: 0755
    recurse: true

- name: 99-loopback.conf exists
  copy:
    content: |
      {
        "cniVersion": "0.3.1",
        "name": "lo",
        "type": "loopback"
      }
    dest: '{{ k8s_node__kubelet_cni_conf_dir }}/99-loopback.conf'
