- name: Docker is installed
  yum:
    name: '{{ k8s_node__docker_package_name }}'
    state: present

- name: DOCKER_NOFILE is set for k8s
  lineinfile:
    path: /etc/sysconfig/docker
    line: DOCKER_NOFILE={{ k8s_node__docker_nofile }}
    state: present

- name: dockerd options are set for k8s
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: "OPTIONS='[^']+'"
    line: OPTIONS='--iptables=false {{ k8s_node__additional_dockerd_options }}'
    state: present

- name: dockerd is running
  systemd:
    name: docker
    daemon_reload: true
    enabled: true
    state: started
