- name: k8s bin dir exists
  file:
    path: '{{ k8s__k8s_bin_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory
- name: kubelet and kube-proxy are installed
  get_url:
    url: '{{ k8s__k8s_bins_download_url_base }}/{{ item.name }}'
    dest: '{{ k8s__k8s_bin_dir }}/{{ item.name }}'
    owner: root
    group: root
    mode: 0755
    checksum: '{{ item.checksum }}'
  loop:
  - name: kubelet
    checksum: '{{ k8s__kubelet_bin_checksum }}'
  - name: kube-proxy
    checksum: '{{ k8s__kube_proxy_bin_checksum }}'
  - name: kubectl
    checksum: '{{ k8s__kubectl_bin_checksum }}'
  - name: kubeadm
    checksum: '{{ k8s__kubeadm_bin_checksum }}'
