- name: Static pod dir exists
  file:
    path: '{{ k8s__static_pod.manifests_path }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  when: k8s__static_pod.enabled

- name: kubelet lib dir exists
  file:
    path: '{{ k8s_node__kubelet_root_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Volume plugin dir exists
  file:
    path: '{{ k8s__volume_plugin_dir }}'
    owner: kubernetes
    group: kubernetes
    mode: 0755
    state: directory

- name: kubelet unit file exists
  template:
    src: systemd_units/kubelet.service.j2
    dest: /etc/systemd/system/{{ k8s__service_name_prefix }}kubelet.service
    owner: root
    group: root
    mode: 0664

- name: kubelet.conf exists
  template:
    src: k8s_configs/kubelet.conf.j2
    dest: '{{ k8s_node__k8s_configs_dir }}/kubelet.conf'
    owner: root
    group: root
    mode: 0644

- name: kubelet is running
  systemd:
    name: '{{ k8s__service_name_prefix }}kubelet'
    daemon_reload: true
    enabled: true
    state: started
