- name: Kernel parametes are tuned
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
  loop: '{{ k8s_node__kernel_params }}'
