- name: pki dir exists
  file:
    path: '{{ etcd__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Keys are installed
  copy:
    src: '{{ item }}'
    dest: '{{ etcd__pki_dir }}'
    owner: etcd
    group: etcd
    mode: 0600
  loop:
  - '{{ k8s__local_shared_dir }}/etcd-ca.key'
  - '{{ k8s__local_shared_dir }}/etcd.key'
  - '{{ k8s__local_shared_dir }}/etcd-peer.key'

- name: Certificates are installed
  copy:
    src: '{{ item }}'
    dest: '{{ etcd__pki_dir }}'
    owner: etcd
    group: etcd
    mode: 0644
  loop:
  - '{{ k8s__local_shared_dir }}/etcd-ca.crt'
  - '{{ k8s__local_shared_dir }}/etcd.crt'
  - '{{ k8s__local_shared_dir }}/etcd-peer.crt'
