- name: etcd unit file exists
  template:
    src: systemd_units/etcd.service.j2
    dest: /etc/systemd/system/{{ k8s__service_name_prefix }}etcd.service
    owner: root
    group: root
    mode: 0664

- name: etcd data directory exists
  file:
    path: '{{ etcd__data_dir }}'
    owner: etcd
    group: etcd
    mode: 0700
    state: directory

- name: etcd is running
  systemd:
    name: '{{ k8s__service_name_prefix }}etcd'
    daemon_reload: true
    enabled: true
    state: started
  async: '{{ host__etcd_start_timeout | default(1) }}'
  poll: '{{ host__etcd_polling_interval | default(0) }}'
