- name: etcd bins
  vars:
    _etcd_archive_basename: etcd-{{ etcd__etcd_version }}-linux-amd64
    _etcd_archive: '{{ _etcd_archive_basename }}.tar.gz'
  block:
  - name: etcd archive is downloaded
    get_url:
      url: '{{ etcd__etcd_archive_download_url_base }}/{{ etcd__etcd_version }}/{{ _etcd_archive }}'
      dest: /tmp/{{ _etcd_archive }}
      checksum: '{{ etcd__etcd_archive_checksum }}'
    register: _get_url_result
  - name: etcd archive is extracted
    unarchive:
      src: /tmp/{{ _etcd_archive }}
      remote_src: true
      dest: /tmp
    when: _get_url_result.changed
  - name: etcd bin dir exists
    file:
      path: '{{ etcd__etcd_bin_dir }}'
      owner: root
      group: root
      mode: 0755
      state: directory
  - name: etcd bins are installed
    copy:
      remote_src: true
      src: /tmp/{{ _etcd_archive_basename }}/{{ item }}
      dest: '{{ etcd__etcd_bin_dir }}'
      owner: root
      group: root
      mode: 0755
    loop:
    - etcd
    - etcdctl
