k8s_master__k8s_bins_download_url_base: https://storage.googleapis.com/kubernetes-release/release/{{ k8s__k8s_version }}/bin/linux/amd64
k8s_master__kube_apiserver_bin_checksum: sha1:853cd4a9ed8f09a07238c874959298506c356da6
k8s_master__kube_controller_manager_bin_checksum: sha1:6d22f1a5c7bbdc30a74f53c23ee9649ff2b50be8
k8s_master__kube_scheduler_bin_checksum: sha1:21199d93abe2f79db8d77aca87682d5834111107
k8s_master__kubectl_bin_checksum: sha1:2a8617a6efb41f2fd8424e14e80267e2c09fe0bf
k8s_master__kubeadm_bin_checksum: sha1:8286906061f9d1752dd6f44f7fc55f0c8f25e0d9

k8s_master__pki_dir: /etc/kubernetes/pki
k8s_master__audit_log_dir: /var/log/kubernetes
k8s_master__kubeconfig_dir: /etc/kubernetes
k8s_master__k8s_configs_dir: /etc/kubernetes

k8s_master__kube_admin_user_uid: 1030
k8s_master__kube_admin_user_gid: 1030

k8s_master__secret_encoding_key: your_32_bytes_secure_private_key

k8s_master__kube_apiserver_audit_log_format: json
k8s_master__kube_apiserver_audit_log_maxage: 30
k8s_master__kube_apiserver_audit_log_maxbackup: 3
k8s_master__kube_apiserver_audit_log_maxsize: 100
k8s_master__kube_apiserver_audit_log_path: '{{ k8s_master__audit_log_dir }}/kube-audit.log'
k8s_master__kube_apiserver_bind_address: 0.0.0.0
k8s_master__kube_apiserver_enable_admission_plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,DenyEscalatingExec,StorageObjectInUseProtection,PodSecurityPolicy
k8s_master__kube_apiserver_etcd_servers:
  auto_set: true
  # auto_set: false
  # servers: https://127.0.0.1:2379
k8s_master__kube_apiserver_insecure_port: 0
k8s_master__kube_apiserver_kubelet_preferred_address_types: InternalIP,ExternalIP,Hostname
k8s_master__kube_apiserver_kubernetes_service_node_port: 0
k8s_master__kube_apiserver_profiling: 'false'
k8s_master__kube_apiserver_repair_malformed_updates: 'false'
k8s_master__kube_apiserver_service_node_port_range: '30000-32767'
k8s_master__kube_apiserver_tls_cipher_suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
k8s_master__kube_apiserver_tls_min_version: VersionTLS12
k8s_master__kube_apiserver_vlog_level: 2
k8s_master__kube_apiserver_restart_sec: 10

k8s_master__kube_controller_manager_bind_address: 127.0.0.1
k8s_master__kube_controller_manager_cluster_signing_duration: 8760h0m0s
k8s_master__kube_controller_manager_controllers: '*,bootstrapsigner,tokencleaner'
k8s_master__kube_controller_manager_enable_hostpath_provisioner: 'true'
k8s_master__kube_controller_manager_node_cidr_mask_size: 24
k8s_master__kube_controller_manager_node_eviction_rate: 0.1
k8s_master__kube_controller_manager_node_monitor_grace_period: 40s
k8s_master__kube_controller_manager_node_monitor_period: 5s
k8s_master__kube_controller_manager_node_startup_grace_period: 1m0s
k8s_master__kube_controller_manager_pod_eviction_timeout: 5m0s
k8s_master__kube_controller_manager_port: 10252
k8s_master__kube_controller_manager_profiling: 'false'
k8s_master__kube_controller_manager_secondary_node_eviction_rate: 0.01
k8s_master__kube_controller_manager_secure_port: 10257
k8s_master__kube_controller_manager_tls_cipher_suites: '{{ k8s_master__kube_apiserver_tls_cipher_suites }}'
k8s_master__kube_controller_manager_tls_min_version: '{{ k8s_master__kube_apiserver_tls_min_version }}'
k8s_master__kube_controller_manager_unhealthy_zone_threshold: 0.55
k8s_master__kube_controller_manager_vlog_level: 2
k8s_master__kube_controller_manager_restart_sec: 10
k8s_master__kube_controller_manager_use_auto_generated_serving_cert: false

k8s_master__kube_scheduler_bind_address: 127.0.0.1
k8s_master__kube_scheduler_healthz_bind_address: 127.0.0.1:10251
k8s_master__kube_scheduler_metrics_bind_address: 127.0.0.1:10247
k8s_master__kube_scheduler_secure_port: 10259
k8s_master__kube_scheduler_tls_cipher_suites: '{{ k8s_master__kube_apiserver_tls_cipher_suites }}'
k8s_master__kube_scheduler_tls_min_version: '{{ k8s_master__kube_apiserver_tls_min_version }}'
k8s_master__kube_scheduler_vlog_level: 2
k8s_master__kube_scheduler_restart_sec: 10
k8s_master__kube_scheduler_use_auto_generated_serving_cert: false
