k8s_master__k8s_bins_download_url_base: https://storage.googleapis.com/kubernetes-release/release/{{ k8s__k8s_version }}/bin/linux/amd64
k8s_master__kube_apiserver_bin_checksum: sha1:cc33fa6ba52aa13ab3e093a9eb4357658591c4b5
k8s_master__kube_controller_manager_bin_checksum: sha1:3db5b809a9ceedb7176aebe2872d2dd34d85d9e8
k8s_master__kube_scheduler_bin_checksum: sha1:591ea21d9ea7d98426299c1fcd713a7a56296090
k8s_master__kubectl_bin_checksum: sha1:76ec5b750a2023f22c0766624189b96c8146bbe5
k8s_master__kubeadm_bin_checksum: sha1:ebfdb3a8ecf7f161f048703d4328bf81bbdbb323

k8s_master__pki_dir: /etc/kubernetes/pki
k8s_master__audit_log_dir: /var/log/kubernetes
k8s_master__kubeconfig_dir: /etc/kubernetes
k8s_master__k8s_configs_dir: /etc/kubernetes

k8s_master__secret_encoding_key: your_32_bytes_secure_private_key

k8s_master__kube_apiserver_audit_log_format: json
k8s_master__kube_apiserver_audit_log_maxage: 30
k8s_master__kube_apiserver_audit_log_maxbackup: 3
k8s_master__kube_apiserver_audit_log_maxsize: 100
k8s_master__kube_apiserver_audit_log_path: '{{ k8s_master__audit_log_dir }}/kube-audit.log'
k8s_master__kube_apiserver_bind_address: 0.0.0.0
k8s_master__kube_apiserver_enable_admission_plugins: NodeRestriction,PodSecurityPolicy
k8s_master__kube_apiserver_etcd_compaction_interval: 5m0s
k8s_master__kube_apiserver_etcd_servers:
  auto_set: true
  # auto_set: false
  # servers: https://127.0.0.1:2379
k8s_master__kube_apiserver_event_ttl: 1h0m0s
k8s_master__kube_apiserver_kubelet_preferred_address_types: InternalIP,ExternalIP,Hostname
k8s_master__kube_apiserver_kubernetes_service_node_port: 0
k8s_master__kube_apiserver_profiling: 'false'
k8s_master__kube_apiserver_service_node_port_range: '30000-32767'
k8s_master__kube_apiserver_tls_cipher_suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
k8s_master__kube_apiserver_tls_min_version: VersionTLS12
k8s_master__kube_apiserver_vlog_level: 2
k8s_master__kube_apiserver_restart_sec: 10

k8s_master__kube_controller_manager_bind_address: 127.0.0.1
k8s_master__kube_controller_manager_cluster_signing_duration: 8760h0m0s
k8s_master__kube_controller_manager_controllers: '*,bootstrapsigner,tokencleaner'
k8s_master__kube_controller_manager_enable_hostpath_provisioner: 'true'
k8s_master__kube_controller_manager_node_cidr_mask_size: 24
k8s_master__kube_controller_manager_node_eviction_rate: 0.1
k8s_master__kube_controller_manager_node_monitor_grace_period: 40s
k8s_master__kube_controller_manager_node_monitor_period: 5s
k8s_master__kube_controller_manager_node_startup_grace_period: 1m0s
k8s_master__kube_controller_manager_pod_eviction_timeout: 5m0s
k8s_master__kube_controller_manager_profiling: 'false'
k8s_master__kube_controller_manager_secondary_node_eviction_rate: 0.01
k8s_master__kube_controller_manager_secure_port: 10257
k8s_master__kube_controller_manager_terminated_pod_gc_threshold: 1250
k8s_master__kube_controller_manager_tls_cipher_suites: '{{ k8s_master__kube_apiserver_tls_cipher_suites }}'
k8s_master__kube_controller_manager_tls_min_version: '{{ k8s_master__kube_apiserver_tls_min_version }}'
k8s_master__kube_controller_manager_unhealthy_zone_threshold: 0.55
k8s_master__kube_controller_manager_vlog_level: 2
k8s_master__kube_controller_manager_restart_sec: 10
k8s_master__kube_controller_manager_use_auto_generated_serving_cert: true

k8s_master__kube_scheduler_bind_address: 127.0.0.1
k8s_master__kube_scheduler_healthz_bind_address: 127.0.0.1:10251
k8s_master__kube_scheduler_metrics_bind_address: 127.0.0.1:10247
k8s_master__kube_scheduler_secure_port: 10259
k8s_master__kube_scheduler_tls_cipher_suites: '{{ k8s_master__kube_apiserver_tls_cipher_suites }}'
k8s_master__kube_scheduler_tls_min_version: '{{ k8s_master__kube_apiserver_tls_min_version }}'
k8s_master__kube_scheduler_vlog_level: 2
k8s_master__kube_scheduler_restart_sec: 10
k8s_master__kube_scheduler_use_auto_generated_serving_cert: true
