- name: coredns manifests dir exists
  file:
    path: '{{ coredns__manifests_dir }}'
    owner: '{{ coredns__manifests_owner }}'
    group: '{{ coredns__manifests_group }}'
    mode: 0755
    state: directory

- name: k8s components are ready
  command: >-
    {{ k8s__k8s_bin_dir }}/kubectl get componentstatuses -o jsonpath='{.items[*].conditions[?(@.type=="Healthy")].status}'
  register: _componentstatuses
  until: _componentstatuses.stdout.find('False') == -1
  retries: 5
  delay: 5
  changed_when: false

- name: CoreDNS-PSP manifest exists
  copy:
    src: coredns_psp.yml
    dest: '{{ coredns__manifests_dir }}'
    owner: '{{ coredns__manifests_owner }}'
    group: '{{ coredns__manifests_group }}'
    mode: 0644
- name: CoreDNS-PSP is deployed
  command: '{{ k8s__k8s_bin_dir }}/kubectl apply -f {{ coredns__manifests_dir }}/coredns_psp.yml'
  register: _apply_result
  changed_when: '" created" in _apply_result.stdout or " configured" in _apply_result.stdout'

- name: CoreDNS-PSP Role manifest exists
  copy:
    src: coredns_psp_role.yml
    dest: '{{ coredns__manifests_dir }}'
    owner: '{{ coredns__manifests_owner }}'
    group: '{{ coredns__manifests_group }}'
    mode: 0644
- name: CoreDNS-PSP Role is deployed
  command: '{{ k8s__k8s_bin_dir }}/kubectl apply -f {{ coredns__manifests_dir }}/coredns_psp_role.yml'
  register: _apply_result
  changed_when: '" created" in _apply_result.stdout or " configured" in _apply_result.stdout'

- name: CoreDNS-PSP/coredns RoleBinding manifest exists
  copy:
    src: coredns_psp_coredns_rolebinding.yml
    dest: '{{ coredns__manifests_dir }}'
    owner: '{{ coredns__manifests_owner }}'
    group: '{{ coredns__manifests_group }}'
    mode: 0644
- name: CoreDNS-PSP/coredns RoleBinding is deployed
  command: '{{ k8s__k8s_bin_dir }}/kubectl apply -f {{ coredns__manifests_dir }}/coredns_psp_coredns_rolebinding.yml'
  register: _apply_result
  changed_when: '" created" in _apply_result.stdout or " configured" in _apply_result.stdout'

- name: CoreDNS manifest exists
  template:
    src: coredns.yml.j2
    dest: '{{ coredns__manifests_dir }}/coredns.yml'
    owner: '{{ coredns__manifests_owner }}'
    group: '{{ coredns__manifests_group }}'
    mode: 0644
- name: CoreDNS is deployed
  command: '{{ k8s__k8s_bin_dir }}/kubectl apply -f {{ coredns__manifests_dir }}/coredns.yml'
  changed_when: '" created" in _apply_result.stdout or " configured" in _apply_result.stdout'
