- name: pki dir exists
  file:
    path: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: openssl config is installed
  copy:
    src: '{{ k8s__local_shared_dir }}/openssl.conf'
    dest: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0644

- name: Keys and certificates for the user 'kubernetes'
  block:
  - name: Keys are installed
    copy:
      src: '{{ k8s__local_shared_dir }}/{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0600
    loop:
    - ca.key
    - kube-apiserver.key
    - apiserver-kubelet-client.key
    - kube-controller-manager.key
    - kube-scheduler.key
    - cloud-controller-manager.key
    - front-proxy-ca.key
    - front-proxy-client.key
    - etcd-client.key
    when: item != "cloud-controller-manager.key" or (k8s__cloud_provider is defined and k8s__cloud_provider == "external")
  - name: Certificates are installed
    copy:
      src: '{{ k8s__local_shared_dir }}/{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644
    loop:
    - ca.crt
    - kube-apiserver.crt
    - apiserver-kubelet-client.crt
    - kube-controller-manager.crt
    - kube-scheduler.crt
    - cloud-controller-manager.crt
    - front-proxy-ca.crt
    - front-proxy-client.crt
    - etcd-client.crt
    when: item != "cloud-controller-manager.crt" or (k8s__cloud_provider is defined and k8s__cloud_provider == "external")
  - name: kube-controller-manager public key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager.pub'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644

- name: Key and certificate for the user 'kube-admin'
  block:
  - name: Admin key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.key'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kube-admin
      group: kube-admin
      mode: 0600
  - name: Admin cert is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.crt'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kube-admin
      group: kube-admin
      mode: 0644
