- name: pki dir exists
  file:
    path: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: openssl config is installed
  copy:
    src: '{{ k8s__local_shared_dir }}/openssl.conf'
    dest: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0644

- name: Keys and certificates for the user 'kubernetes'
  block:
  - name: Keys are installed
    copy:
      src: '{{ k8s__local_shared_dir }}/{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0600
    loop:
    - ca.key
    - kube-apiserver.key
    - apiserver-kubelet-client.key
    - kube-controller-manager-client.key
    - kube-scheduler-client.key
    - front-proxy-ca.key
    - front-proxy-client.key
    - etcd-client.key
  - name: Certificates are installed
    copy:
      src: '{{ k8s__local_shared_dir }}/{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644
    loop:
    - ca.crt
    - kube-apiserver.crt
    - apiserver-kubelet-client.crt
    - kube-controller-manager-client.crt
    - kube-scheduler-client.crt
    - front-proxy-ca.crt
    - front-proxy-client.crt
    - etcd-client.crt
  - name: kube-controller-manager public key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-client.pub'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644

- name: Key and certificate for the admin kubeconfig
  block:
  - name: Admin key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.key'
      dest: '{{ k8s_master__pki_dir }}'
      owner: root
      group: root
      mode: 0600
  - name: Admin cert is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.crt'
      dest: '{{ k8s_master__pki_dir }}'
      owner: root
      group: root
      mode: 0644

- name: Server keys and certificates for kube-controller-manager
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-{{ ansible_facts.fqdn }}.key'
      dest: '{{ k8s_node__pki_dir }}/kube-controller-manager.key'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-{{ ansible_facts.fqdn }}.crt'
      dest: '{{ k8s_node__pki_dir }}/kube-controller-manager.crt'
      owner: root
      group: root
      mode: 0644
  when: not k8s_master__kube_controller_manager_use_auto_generated_serving_cert

- name: Server keys and certificates for kube-scheduler
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-scheduler-{{ ansible_facts.fqdn }}.key'
      dest: '{{ k8s_node__pki_dir }}/kube-scheduler.key'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-scheduler-{{ ansible_facts.fqdn }}.crt'
      dest: '{{ k8s_node__pki_dir }}/kube-scheduler.crt'
      owner: root
      group: root
      mode: 0644
  when: not k8s_master__kube_scheduler_use_auto_generated_serving_cert
