- name: pki dir exists
  file:
    path: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: openssl config is installed
  copy:
    src: '{{ k8s__local_shared_dir }}/openssl.conf'
    dest: '{{ k8s_master__pki_dir }}'
    owner: root
    group: root
    mode: 0644

- name: Keys and certificates for the user 'kubernetes'
  block:
  - name: Keys are installed
    copy:
      src: '{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0600
    loop:
    - '{{ k8s__local_shared_dir }}/ca.key'
    - '{{ k8s__local_shared_dir }}/kube-apiserver.key'
    - '{{ k8s__local_shared_dir }}/apiserver-kubelet-client.key'
    - '{{ k8s__local_shared_dir }}/kube-controller-manager-client.key'
    - '{{ k8s__local_shared_dir }}/kube-scheduler-client.key'
    - '{{ k8s__local_shared_dir }}/front-proxy-ca.key'
    - '{{ k8s__local_shared_dir }}/front-proxy-client.key'
    - '{{ k8s__local_shared_dir }}/etcd-client.key'
  - name: Certificates are installed
    copy:
      src: '{{ item }}'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644
    loop:
    - '{{ k8s__local_shared_dir }}/ca.crt'
    - '{{ k8s__local_shared_dir }}/kube-apiserver.crt'
    - '{{ k8s__local_shared_dir }}/apiserver-kubelet-client.crt'
    - '{{ k8s__local_shared_dir }}/kube-controller-manager-client.crt'
    - '{{ k8s__local_shared_dir }}/kube-scheduler-client.crt'
    - '{{ k8s__local_shared_dir }}/front-proxy-ca.crt'
    - '{{ k8s__local_shared_dir }}/front-proxy-client.crt'
    - '{{ k8s__local_shared_dir }}/etcd-client.crt'
  - name: kube-controller-manager public key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-client.pub'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kubernetes
      group: kubernetes
      mode: 0644

- name: Key and certificate for the user 'kube-admin'
  block:
  - name: Admin key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.key'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kube-admin
      group: kube-admin
      mode: 0600
  - name: Admin cert is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/admin.crt'
      dest: '{{ k8s_master__pki_dir }}'
      owner: kube-admin
      group: kube-admin
      mode: 0644

- name: Server keys and certificates for kube-controller-manager
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-{{ ansible_facts.fqdn }}.key'
      dest: '{{ k8s_node__pki_dir }}/kube-controller-manager.key'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-controller-manager-{{ ansible_facts.fqdn }}.crt'
      dest: '{{ k8s_node__pki_dir }}/kube-controller-manager.crt'
      owner: root
      group: root
      mode: 0644

- name: Server keys and certificates for kube-scheduler
  block:
  - name: Key is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-scheduler-{{ ansible_facts.fqdn }}.key'
      dest: '{{ k8s_node__pki_dir }}/kube-scheduler.key'
      owner: root
      group: root
      mode: 0600
  - name: Certificate is installed
    copy:
      src: '{{ k8s__local_shared_dir }}/kube-scheduler-{{ ansible_facts.fqdn }}.crt'
      dest: '{{ k8s_node__pki_dir }}/kube-scheduler.crt'
      owner: root
      group: root
      mode: 0644
