- name: User 'kubernetes'
  block:
  - name: Group "kubernetes" exists
    group:
      name: kubernetes
      gid: '{{ k8s__kubernetes_user_gid }}'
      system: true
      state: present
  - name: User 'kubernetes' exists
    user:
      name: kubernetes
      uid: '{{ k8s__kubernetes_user_uid }}'
      group: kubernetes
      create_home: false
      shell: /sbin/nologin
      system: true
      state: present
