- name: Volume plugin dir exists
  file:
    path: '{{ k8s__volume_plugin_dir }}'
    owner: kubernetes
    group: kubernetes
    mode: 0755
    state: directory

- name: kube-controller-manager unit file exists
  template:
    src: systemd_units/kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: 0664

- name: kube-controller-manager is running
  systemd:
    name: kube-controller-manager
    daemon_reload: true
    enabled: true
    state: started
