- import_tasks: kubernetes_user_exists.yml
  tags: users
- import_tasks: certs_and_keys_generated.yml
  tags: pki
- import_tasks: k8s_bins_installed.yml
  tags: bins
- import_tasks: kubeconfigs_generated.yml
  tags: kubeconfigs
- import_tasks: kube_apiserver_started.yml
  tags: services
- import_tasks: kube_controller_manager_started.yml
  tags: services
- import_tasks: kube_scheduler_started.yml
  tags: services
- import_tasks: tls_bootstrapping_configured.yml
  run_once: true
  tags: tls_bootstrapping
- import_tasks: helm_installed.yml
  tags: helm
