etcd__etcd_version: v3.4.0
etcd__etcd_archive_download_url_base: https://github.com/coreos/etcd/releases/download
etcd__etcd_archive_checksum: sha1:af01072da1dd5c74d83ca45fe52c304afbce15a2
etcd__pki_dir: /etc/kubernetes/pki

etcd__data_dir: /var/lib/etcd
etcd__etcd_bin_dir: /usr/bin
etcd__listen_client_urls: https://{{ host__public_address }}:{{ host__etcd_server_port }},https://127.0.0.1:{{ host__etcd_server_port }}
etcd__advertise_client_urls: https://{{ host__public_address }}:{{ host__etcd_server_port }}
etcd__listen_peer_urls: https://{{ host__public_address }}:{{ host__etcd_peer_port }}
etcd__initial_advertise_peer_urls: https://{{ host__public_address }}:{{ host__etcd_peer_port }}
etcd__cluster_token: '{{ k8s__k8s_cluster_name }}_8198f9e6ac'
etcd__initial_cluster:
  auto_set: true
  # auto_set: false
  # members: {{ ansible_facts.fqdn }}=https://127.0.0.1:{{ host__etcd_peer_port }}
etcd__max_wals: 5
etcd__snapshot_count: 5000
etcd__max_snapshots: 5
etcd__quota_backend_bytes: 0
# etcd__quota_backend_bytes: -1 # disable quotas
# etcd__quota_backend_bytes: 8589934592 # 8GB (maximum)
etcd__restart_sec: 10
