- name: host__public_address is set
  set_fact:
    host__public_address: '{{ ansible_facts.default_ipv4.address }}'
  when: host__public_address is undefined

- name: /etc/hosts has entries needed
  lineinfile:
    path: /etc/hosts
    line: '{{ item }}'
    state: present
  loop: '{{ base__hosts_entries }}'

- name: YUM repositories needed are enabled
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: '{{ item.gpgkey }}'
    gpgcheck: '{{ item.gpgcheck }}'
    enabled: true
  loop: '{{ base__yum_repos_to_enable }}'

- name: YUM repositories unneeded are disabled
  ini_file:
    path: '{{ item.path }}'
    section: '{{ item.name }}'
    option: enabled
    value: 0
  loop: '{{ base__yum_repos_to_disable }}'

- name: ntp is setup
  block:
  - name: chrony is installed
    yum:
      name: chrony
      state: latest
  - name: chrony is configured
    template:
      src: chrony/chrony.conf.j2
      dest: /etc/chrony.conf
  - name: chronyd is running and enabled
    service:
      name: chronyd
      state: started
      enabled: true
  when: base__ntp_servers

- name: swap off
  block:
  - name: swap doesn't exist in fstab
    mount:
      path: swap
      fstype: swap
      state: absent
  - name: Check if Azure Linux conf exists
    stat:
      path: /etc/waagent.conf
    register: _stat_result
  - name: Swap is disabled in Azure Linux conf
    ini_file:
      path: /etc/waagent.conf
      section: null
      option: ResourceDisk.EnableSwap
      value: 'n'
      no_extra_spaces: true
    when: _stat_result.stat.exists
  - name: check swap devices
    command: swapon -s
    register: swap_devices
    changed_when: false
  - name: swapoff -a
    command: swapoff -a
    when: swap_devices.stdout != ""
  when: host__is_k8s_node

- name: SELinux is configured
  selinux:
    policy: '{{ base__selinux.policy }}'
    state: '{{ base__selinux.state }}'
  when: base__selinux

- name: kernel modules
  block:
  - name: Required kernel modules are loaded
    modprobe:
      name: '{{ item }}'
      state: present
    loop: '{{ base__kernel_modules_to_load }}'
  - name: Required kernel modules are loaded on boot
    lineinfile:
      path: /etc/modules-load.d/k8s.conf
      line: '{{ item }}'
      state: present
      create: true
    loop: '{{ base__kernel_modules_to_load }}'
  when: host__is_k8s_node

- name: Kernel parametes are tuned
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
  loop: '{{ base__kernel_params }}'
  when: host__is_k8s_node

- name: firewalld is disabled
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: base__disable_firewalld

- name: The server is rebooted
  block:
  - name: Reboot is started
    shell: sleep 2 && shutdown -r now
    async: 1
    poll: 0
    sudo: true
    ignore_errors: true
  - name: The server is up again
    wait_for:
      port: '{{ ansible_port | default(ansible_ssh_port) | default(22) }}'
      host: '{{ ansible_host }}'
      state: started
      delay: '{{ base__reboot_polling_delay }}'
      timeout: '{{ base__reboot_polling_timeout }}'
    delegate_to: 127.0.0.1
