dev_env__ntp_servers:
- server 0.rhel.pool.ntp.org iburst
- server 1.rhel.pool.ntp.org iburst
- server 2.rhel.pool.ntp.org iburst
- server 3.rhel.pool.ntp.org iburst

dev_env__dry_ver: v0.9-beta.4
dev_env__dry_download_url: https://github.com/moncho/dry/releases/download/{{ dev_env__dry_ver }}/dry-linux-amd64
dev_env__dry_checksum: sha1:96ee772763933187c280d55a23c54321e3e20f4f

dev_env__kube_prompt_ver: v1.0.3
dev_env__kube_prompt_download_url: https://github.com/c-bata/kube-prompt/releases/download/{{ dev_env__kube_prompt_ver }}/kube-prompt_{{ dev_env__kube_prompt_ver }}_linux_amd64.zip
dev_env__kube_prompt_checksum: sha1:bc486371ba54995055b60bb72f476f65fa87ac4d

dev_env__helm_ver: v2.9.1
dev_env__helm_download_url: https://storage.googleapis.com/kubernetes-helm/helm-{{ dev_env__helm_ver }}-linux-amd64.tar.gz
dev_env__helm_checksum: sha256:56ae2d5d08c68d6e7400d462d6ed10c929effac929fedce18d2636a9b4e166ba

dev_env__stern_ver: 1.6.0
dev_env__stern_download_url: https://github.com/wercker/stern/releases/download/{{ dev_env__stern_ver }}/stern_linux_amd64
dev_env__stern_checksum: sha1:134ad605ffdf90f4969f84f33fb29f34ea4cc79f

dev_env__jq_ver: 1.5
dev_env__jq_download_url: https://github.com/stedolan/jq/releases/download/jq-{{ dev_env__jq_ver }}/jq-linux64
dev_env__jq_checksum: sha1:d8e36831c3c94bb58be34dd544f44a6c6cb88568

dev_env__yum_pkgs_to_install:
- bind-utils
- nmap
- vim
- yum-utils
- tcpdump
- unzip
- git
- bash-completion
