- name: chrony is installed
  yum:
    name: chrony
    state: latest

- name: chrony is configured
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony.conf

- name: chrony is running and enabled
  service:
    name: chrony
    state: started
    enabled: true
