k8s_node__kernel_params:
- name: fs.file-max
  value: 1050000
- name: vm.max_map_count  # Elasticsearch
  value: 262144

k8s_node__yum_install_dependencies: true

k8s_node__k8s_bins_download_url_base: https://storage.googleapis.com/kubernetes-release/release/{{ k8s__k8s_version }}/bin/linux/amd64
k8s_node__kubelet_bin_checksum: sha1:4f25aa74a3ed9afd0991c976c44550e7c816770b
k8s_node__kube_proxy_bin_checksum: sha1:d5bfcbf6135f497676839f912a2f426d68e69609

k8s_node__runc_bin_dir: /usr/bin
k8s_node__runc_version: v1.0.0-rc8
k8s_node__runc_download_url: https://github.com/opencontainers/runc/releases/download/{{ k8s_node__runc_version }}/runc.amd64
k8s_node__runc_checksum: sha1:3e1981e48c85eda85a692250ff9fa037465bd809

k8s_node__containerd_bin_dir: /usr/bin
k8s_node__containerd_conf: /etc/containerd/config.toml
k8s_node__containerd_root_dir: /var/lib/k8s-containerd
k8s_node__containerd_state_dir: /run/k8s-containerd
k8s_node__containerd_opt_dir: /opt/k8s-containerd
k8s_node__containerd_version: 1.2.9
k8s_node__containerd_archive_download_url_base: https://github.com/containerd/containerd/releases/download/v{{ k8s_node__containerd_version }}/containerd-{{ k8s_node__containerd_version }}.linux-amd64.tar.gz
k8s_node__containerd_archive_checksum: sha1:cf00f204b3aad3d953ad0601dc43930101863a7c
k8s_node__containerd_restart_sec: 10

k8s_node__cni_version: v0.6.0
k8s_node__cni_archive_download_url_base: https://github.com/containernetworking/cni/releases/download
k8s_node__cni_archive_checksum: sha1:201d934018af9097d6719d70688dabd578ee2b2e

k8s_node__cni_plugins_version: v0.8.2
k8s_node__cni_plugins_archive_download_url_base: https://github.com/containernetworking/plugins/releases/download
k8s_node__cni_plugins_archive_checksum: sha1:e2b4b541218d611710a8ccbec6c2b34decea2884

k8s_node__kubeconfig_dir: /etc/kubernetes
k8s_node__k8s_configs_dir: /etc/kubernetes
k8s_node__pki_dir: /etc/kubernetes/pki

k8s_node__kubelet_address: 0.0.0.0
k8s_node__kubelet_cert_dir: '{{ k8s_node__pki_dir }}'
k8s_node__kubelet_cni_bin_dir: /opt/cni/bin
k8s_node__kubelet_cni_conf_dir: /etc/cni/net.d
k8s_node__kubelet_cgroup_driver: cgroupfs
k8s_node__kubelet_container_log_max_files: 5
k8s_node__kubelet_container_log_max_size: 10Mi
k8s_node__kubelet_enforce_node_allocatable:
- pods
k8s_node__kubelet_eviction_hard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
# k8s_node__kubelet_eviction_soft:
#   imagefs.available: 15%
#   memory.available: 100Mi
#   nodefs.available: 10%
#   nodefs.inodesFree: 5%
# k8s_node__kubelet_eviction_soft_grace_period:
#   imagefs.available: 1m
#   memory.available: 1m
#   nodefs.available: 1m
#   nodefs.inodesFree: 1m
k8s_node__kubelet_eviction_pressure_transition_period: 5m
k8s_node__kubelet_eviction_max_pod_grace_period: 0
# k8s_node__kubelet_eviction_minimum_reclaim:
#   imagefs.available: 1Gi
#   memory.available: 500Mi
#   nodefs.available: 15%
#   nodefs.inodesFree: 10%
k8s_node__kubelet_fail_swap_on: true
k8s_node__kubelet_hairpin_mode: hairpin-veth
k8s_node__kubelet_healthz_bind_address: 127.0.0.1
k8s_node__kubelet_healthz_port: 10248
k8s_node__kubelet_image_minimum_gc_age: 2m
k8s_node__kubelet_image_gc_high_threshold_percent: 85
k8s_node__kubelet_image_gc_low_threshold_percent: 80
k8s_node__kubelet_max_open_files: 1010000
k8s_node__kubelet_max_pods: 110
k8s_node__kubelet_node_status_update_frequency: 10s
k8s_node__kubelet_pod_infra_container_image: k8s.gcr.io/pause-amd64:3.1
k8s_node__kubelet_pod_pids_limit: 512
k8s_node__kubelet_rotate_certificates: true
k8s_node__kubelet_runtime_request_timeout: 10m
k8s_node__kubelet_tls_cipher_suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
k8s_node__kubelet_tls_min_version: VersionTLS12
k8s_node__kubelet_vlog_level: 2
k8s_node__kubelet_restart_sec: 10

k8s_node__kube_proxy_bind_address: 127.0.0.1
k8s_node__kube_proxy_enable_profiling: false
k8s_node__kube_proxy_healthz_bind_address: 127.0.0.1:10256
k8s_node__kube_proxy_ipvs_exclude_cidrs: []
k8s_node__kube_proxy_ipvs_min_sync_period: 0s
k8s_node__kube_proxy_ipvs_scheduler: rr
k8s_node__kube_proxy_ipvs_sync_period: 30s
k8s_node__kube_proxy_metrics_bind_address: 127.0.0.1:10249
k8s_node__kube_proxy_mode: ipvs
k8s_node__kube_proxy_port_range: '0-0'
k8s_node__kube_proxy_vlog_level: 2
k8s_node__kube_proxy_restart_sec: 10
